"""
    Purpose:
        File for holding custom exception types that will be generated by the
        avro_helpers libraries
"""


class AvscInvalid(Exception):
    """
    Purpose:
        The AvscInvalid will be raised when reading the .avsc raises an exception
    """

    pass


class AvscNotFound(Exception):
    """
    Purpose:
        The AvscNotFound will be raised when trying to Read/Write a .avro file
        without a schema file
    """

    pass

